import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import { start } from "../lib/twin";
let started = false;

const Home: NextPage = () => {
  useEffect(() => {
    if (!started) {
      start();
      started = true;
    }

    return () => {
      // second
    };
  }, []);

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div id="info">
          <a
            href="https://threejs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            three.js
          </a>{" "}
          car materials
          <br />
          Ferrari 458 Italia model by{" "}
          <a
            href="https://sketchfab.com/models/57bf6cc56931426e87494f554df1dab6"
            target="_blank"
            rel="noopener noreferrer"
          >
            vicent091036
          </a>
          <br />
          <br />
          <span className="colorPicker">
            <input id="body-color" type="color" value="#ff0000"></input>
            <br />
            Body
          </span>
          <span className="colorPicker">
            <input id="details-color" type="color" value="#ffffff"></input>
            <br />
            Details
          </span>
          <span className="colorPicker">
            <input id="glass-color" type="color" value="#ffffff"></input>
            <br />
            Glass
          </span>
        </div>

        <div id="container"></div>
      </main>

      {/* <footer className={styles.footer}></footer> */}
    </div>
  );
};

export default Home;
